var appleDevices = {
	'iPhone 6' : ['iPhone7,2'],
	'iPhone 6 Plus' : ['iPhone7,1'],
	'iPhone 6s' : ['iPhone8,1'],
	'iPhone 6s Plus' : ['iPhone8,2'],
	'iPhone SE' : ['iPhone8,4'],
	'iPhone (1st generation)' : ['iPhone1,1'],
	'iPhone 3G' : ['iPhone1,2'],
	'iPhone 3GS' : ['iPhone2,1'],
	'iPhone 4' : ['iPhone3,1' , 'iPhone3,2' , 'iPhone3,3'],
	'iPhone 4s' : ['iPhone4,1'],
	'iPhone 5' : ['iPhone5,1' , 'iPhone5,2'],
	'iPhone 5c' : ['iPhone5,3' , 'iPhone5,4'],
	'iPhone 5s' : ['iPhone6,1' , 'iPhone6,2'],
	'iPod (1st generation)' : ['iPod1,1'],
	'iPod (2nd generation)' : ['iPod2,1'],	
	'iPod (3rd generation)' : ['iPod3,1'],	
	'iPod (4th generation)' : ['iPod4,1'],	
	'iPod (5th generation)' : ['iPod5,1'],	
	'iPod (6th generation)' : ['iPod7,1'],
	'iPad (1st generation)' : ['iPad1,1'],
	'iPad 2' : ['iPad2,1' , 'iPad2,2' , 'iPad2,3' , 'iPad2,4'],
	'iPad (3rd generation)' : ['iPad3,1' , 'iPad3,2' , 'iPad3,3'],
	'iPad (4th generation)' : ['iPad3,4' , 'iPad3,5' , 'iPad3,6'],
	'iPad Air' : ['iPad4,1' , 'iPad4,2' , 'iPad4,3'],
	'iPad Air 2' : ['iPad5,3' , 'iPad5,4'],
	'iPad mini (1st generation)' : ['iPad2,5' , 'iPad2,6' , 'iPad2,7'],
	'iPad mini 2' : ['iPad4,4' , 'iPad4,5' , 'iPad4,6'],
	'iPad mini 3' : ['iPad4,7' , 'iPad4,8' , 'iPad4,9'],
	'iPad mini 4' : ['iPad5,1' , 'iPad5,2'],
	'iPad Pro (12.9 inch)' : ['iPad6,7' , 'iPad6,8'],
	'iPad Pro (9.7 inch)' : ['iPad6,3' , 'iPad6,4'],
	'Apple TV (2nd generation)' : ['AppleTV2,1'],
	'Apple TV (3rd generation)' : ['AppleTV3,1'],
	'Apple TV (3rd generation Rev A)' : ['AppleTV3,2'],
	'Apple TV (4th generation)' : ['AppleTV5,3']
}
